server:
  port: 8084

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_dashboard?currentSchema=finance
    username: finance
    password: finance
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: finance
    open-in-view: false
  flyway:
    enabled: true
    schemas: finance
    default-schema: finance
    locations: classpath:db/migration

platform:
  security:
    dev-user-sub-enabled: true

logging:
  level:
    org.springframework.security: INFO
